CREATE TABLE activity_log (
	id SERIAL PRIMARY KEY,
	card_id INT REFERENCES cards(id) ON DELETE CASCADE,
	action_log VARCHAR(255) NOT NULL,
	make_by INT REFERENCES users(id),
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)