CREATE TABLE users (
	id SERIAL PRIMARY KEY,
	name TEXT UNIQUE,
	email TEXT UNIQUE,
	password VARCHAR(127),
	createdat TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updatedat TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	role INT
)